---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: osctl-restore
  namespace: infra-elklogs
  labels:
    job: osctl-restore
    service: osctl
spec:
  schedule: "0 23 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      labels:
        job: osctl-restore
        service: osctl
    spec:
      activeDeadlineSeconds: 86000
      template:
        metadata:
          labels:
            job: osctl-restore
            service: osctl
        spec:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: node-role.flant.com/odfe-common
                    operator: In
                    values: [""]
                - matchExpressions:
                  - key: node-role/odfe-common
                    operator: In
                    values: [""]
          tolerations:
          - key: dedicated.flant.com
            operator: Equal
            value: odfe-common
            effect: NoSchedule
          - key: dedicated
            operator: Equal
            value: odfe-common
            effect: NoSchedule
          restartPolicy: Never
          containers:
          - name: osctl
            image: docker-flant.art.lmru.tech/lmru/devops/opensearch--osctl:1.0.4
            imagePullPolicy: IfNotPresent
            workingDir: /app
            command:
            - /app/osctl
            args:
            - restore
            - --snap-repo=s3-backup-old
            - "--index-filter=other-kong-x1-fluentd-2026.*,other-kong-yc-a-stage-fluentd-2026.*,other-kong-yc-fluentd-2026.*,other-kong-x2-fluentd-2026.*,kong-yc-a-stage-fluentd-doc-2026.*,kong-x2-fluentd-doc-2026.*,kong-x1-fluentd-doc-2026.*,kong-yc-fluentd-doc-2026.*"
            volumeMounts:
            - name: osctl-config
              mountPath: /app/config.yaml
              subPath: config.yml
              readOnly: true
            - name: certs
              mountPath: /etc/ssl/certs/admin-crt.pem
              subPath: admin-crt.pem
              readOnly: true
            - name: certs
              mountPath: /etc/ssl/certs/admin-key.pem
              subPath: admin-key.pem
              readOnly: true
          volumes:
          - name: osctl-config
            configMap:
              name: osctl-configmap
              defaultMode: 420
          - name: certs
            secret:
              secretName: opendistro-tls-data
              defaultMode: 420
