{{- if and .Values.opendistro.enabled .Values.kibana.enabled .Values.recoverer.enabled .Values.opendistro.s3_backup.enabled .Values.kibana.multidomain.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: osctl-restarter-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: osctl-restarter-role-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "update"]
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["list"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "update"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: osctl-restarter-rb-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: osctl-restarter-{{ .Release.Namespace }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: osctl-restarter-role-{{ .Release.Namespace }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
