apiVersion: v1
kind: ConfigMap
metadata:
  name: osctl-config
  namespace: infra-elklogs
data:
  config.yaml: |
    # Configuration File for osctl

    # Action to execute (optional) - if set, osctl will automatically run this command
    # Available actions: snapshots, snapshot-manual, snapshotsdelete, snapshotschecker, 
    #                   indicesdelete, retention, dereplicator, coldstorage, 
    #                   extracteddelete, danglingchecker
    action: "snapshot"

    # Common settings shared across all commands
    opensearch_url: "https://opendistro:9200"
    cert_file: "/etc/ssl/certs/admin-crt.pem"
    key_file: "/etc/ssl/certs/admin-key.pem"
    ca_file: "/etc/ssl/certs/elk-root-ca.pem"
    timeout: "300s"
    retry_attempts: 3
    date_format: "%Y.%m.%d"
    dry_run: false
    snapshot_repo: "s3-backup"

    # madison alerts settings
    madison_url: "https://madison.flant.com/api/events/custom/"
    madison_key: ""
    osd_url: ""

    # Command-specific configurations

    # coldstorage
    cold_attribute: "cold"
    hot_count: 3

    # danglingchecker

    # datasource
    data_source_name: "opensearch-logs"

    # dereplicator:
    dereplicator_days_count: 2
    dereplicator_use_snapshot: false


    # extracteddelete:
    opensearch_recoverer_url: "https://opendistro-recoverer:9200"
    extracted_pattern: "extracted_"
    extracted_days: 2
    recoverer_date_format: "%d-%m-%Y"

    # indexpatterns:

    # indicesdelete:
    # Uses osctl-indices-config for detailed configuration

    # retention:
    retention_threshold: 75.0

    # sharding:

    # snapshot:
    # Uses osctl-indices-config for detailed configuration

    # snapshotchecker:
    # Uses osctl-indices-config for detailed configuration

    # snapshotdelete:
    # Uses osctl-indices-config for detailed configuration

    # snapshotmanual:
    snapshot_manual_kind: "prefix"
    snapshot_manual_value: ""
    snapshot_manual_name: ""
    snapshot_manual_system: false
    snapshot_manual_days_count: 7
    snapshot_manual_count_s3: 0


  osctlindicesconfig.yaml: |
    ---
    s3_snapshots:
      unit_count:
        all: {{ .Values.opendistro.curator.s3_snapshots.unit_count.all | default 60 }}
        unknown: {{ .Values.opendistro.curator.s3_snapshots.unit_count.unknown | default 7 }}
    unknown:
      days_count: {{ .Values.opendistro.curator.unknown.days_count | default 7 }}
      snapshot: {{ .Values.opendistro.curator.unknown.snapshot | default true }}
    indices:
{{- range .Values.opendistro.curator.indices }}
      - kind: {{ .kind }}
        value: {{ .value }}
        {{- if .name }}
        name: {{ .name }}
        {{- end }}
        system: {{ .system | default false }}
        days_count: {{ .days_count | default 7 }}
        snapshot: {{ .snapshot | default true }}
        {{- if .snapshot_count_s3 }}
        snapshot_count_s3: {{ .snapshot_count_s3 }}
        {{- end }}
{{- end }}
