name: Go

on:
  push:
    tags:
      - '**'

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.25

    - name: Build
      run: |
        versionflags="-X 'github.com/flant/osctl/pkg/util.Version=$GITHUB_REF_NAME' -X 'github.com/flant/osctl/pkg/util.Revision=$GITHUB_SHA' -X 'github.com/flant/osctl/pkg/util.Branch=$GITHUB_REF_NAME' -X 'github.com/flant/osctl/pkg/util.BuildUser=$GITHUB_ACTOR' -X 'github.com/flant/osctl/pkg/util.BuildDate=$(date +%Y%m%d%H%M)'"
        for GOOS in linux; do
          for GOARCH in amd64 arm64; do
            export GOOS GOARCH
            CGO_ENABLED=0 go build -v -a -tags netgo -ldflags="-extldflags '-static' -s -w $versionflags" -o build/osctl-${GOOS}-${GOARCH} cmd/main.go
          done
        done
        cd build; sha256sum * > sha256sums.txt

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        generate_release_notes: true
        token: ${{ secrets.GITHUB_TOKEN }}
        files: |
          build/*